"""Standalone seed data for the future artist ecosystem.

This file is intentionally not wired into the simulator yet.
It gives us a clean place to shape roster values before we connect the system.
"""

from dataclasses import dataclass, replace
import random

GENRES = [
    "pop",
    "hip hop",
    "rock",
    "jazz",
    "classical",
    "electronic",
    "r&b",
    "metal",
    "country",
    "reggae",
    "folk",
    "blues",
    "punk",
    "soul",
    "experimental",
]

THEMES = [
    "heartbreak",
    "party",
    "protest",
    "nostalgia",
    "love",
    "existential",
    "street life",
    "spirituality",
    "rage",
    "euphoria",
]

SKILLS = ["lyrics", "vocals", "production", "mix/master"]


@dataclass(frozen=True)
class EcosystemArtistSeed:
    name: str
    role: str
    genres: dict[str, int]
    themes: dict[str, int]
    skills: dict[str, int]
    popularity: float
    quality_consistency: int
    release_tendency: int
    friendliness: int
    controversy: int
    aggression: int
    feature_cost: int
    battle_skills: int = 50
    project_ability: int | None = None
    gender: str = "male"
    sexuality: str | None = None
    romance_preference: str | None = None


VALID_ROMANCE_PREFERENCES = ("prefers_male", "prefers_female", "prefers_both")


def _stable_seed_rng(label: str) -> random.Random:
    value = 0
    for ch in label:
        value = (value * 131 + ord(ch)) & 0xFFFFFFFF
    return random.Random(value)


def _hidden_romance_preference_for_name(name: str) -> str:
    rng = _stable_seed_rng("romance-pref:" + str(name))
    return rng.choices(
        VALID_ROMANCE_PREFERENCES,
        weights=[18, 74, 8],
        k=1,
    )[0]


def proficiencies(base: int, overrides: dict[str, int]) -> dict[str, int]:
    data = {key: base for key in GENRES + THEMES + SKILLS}
    data.update(overrides)
    return data


def genre_profile(overrides: dict[str, int], base: int = 18) -> dict[str, int]:
    return {genre: proficiencies(base, overrides)[genre] for genre in GENRES}


def theme_profile(overrides: dict[str, int], base: int = 18) -> dict[str, int]:
    return {theme: proficiencies(base, overrides)[theme] for theme in THEMES}


def skill_profile(overrides: dict[str, int], base: int = 20) -> dict[str, int]:
    return {skill: proficiencies(base, overrides)[skill] for skill in SKILLS}


ARTIST_ECOSYSTEM_SEEDS: list[EcosystemArtistSeed] = [
    EcosystemArtistSeed(
        name="Eminem",
        role="rapper",
        genres=genre_profile({"hip hop": 98, "rock": 42, "pop": 34}),
        themes=theme_profile({"rage": 94, "protest": 82, "street life": 88, "nostalgia": 77}),
        skills=skill_profile({"lyrics": 99, "vocals": 82, "production": 58, "mix/master": 50}),
        popularity=91.0,
        quality_consistency=82,
        release_tendency=14,
        friendliness=36,
        controversy=73,
        aggression=95,
        feature_cost=280000,
    ),
    EcosystemArtistSeed(
        name="Kendrick Lamar",
        role="rapper",
        genres=genre_profile({"hip hop": 99, "jazz": 55, "soul": 58, "experimental": 50}),
        themes=theme_profile({"protest": 98, "street life": 96, "existential": 91, "spirituality": 84}),
        skills=skill_profile({"lyrics": 99, "vocals": 84, "production": 62, "mix/master": 52}),
        popularity=94.0,
        quality_consistency=96,
        release_tendency=5,
        friendliness=54,
        controversy=64,
        aggression=90,
        feature_cost=400000,
    ),
    EcosystemArtistSeed(
        name="J. Cole",
        role="rapper",
        genres=genre_profile({"hip hop": 96, "r&b": 46, "soul": 41}),
        themes=theme_profile({"street life": 84, "nostalgia": 78, "protest": 70, "love": 54}),
        skills=skill_profile({"lyrics": 95, "vocals": 77, "production": 74, "mix/master": 55}),
        popularity=88.0,
        quality_consistency=84,
        release_tendency=24,
        friendliness=67,
        controversy=28,
        aggression=62,
        feature_cost=180000,
    ),
    EcosystemArtistSeed(
        name="Drake",
        role="rapper-singer",
        genres=genre_profile({"hip hop": 89, "pop": 81, "r&b": 86, "electronic": 40}),
        themes=theme_profile({"love": 92, "heartbreak": 87, "party": 82, "nostalgia": 72}),
        skills=skill_profile({"lyrics": 78, "vocals": 86, "production": 60, "mix/master": 52}),
        popularity=98.0,
        quality_consistency=68,
        release_tendency=45,
        friendliness=42,
        controversy=85,
        aggression=76,
        feature_cost=450000,
    ),
    EcosystemArtistSeed(
        name="Tyler, The Creator",
        role="artist-producer",
        genres=genre_profile({"hip hop": 88, "soul": 63, "experimental": 93, "pop": 54}),
        themes=theme_profile({"existential": 84, "nostalgia": 86, "love": 60, "euphoria": 72}),
        skills=skill_profile({"lyrics": 87, "vocals": 74, "production": 95, "mix/master": 78}),
        popularity=87.0,
        quality_consistency=90,
        release_tendency=15,
        friendliness=48,
        controversy=52,
        aggression=58,
        feature_cost=220000,
    ),
    EcosystemArtistSeed(
        name="Baby Keem",
        role="rapper",
        genres=genre_profile({"hip hop": 90, "experimental": 64, "pop": 34}),
        themes=theme_profile({"rage": 82, "street life": 70, "party": 63, "euphoria": 68}),
        skills=skill_profile({"lyrics": 74, "vocals": 76, "production": 62, "mix/master": 48}),
        popularity=72.0,
        quality_consistency=66,
        release_tendency=20,
        friendliness=58,
        controversy=41,
        aggression=69,
        feature_cost=80000,
    ),
    EcosystemArtistSeed(
        name="Travis Scott",
        role="rapper-producer",
        genres=genre_profile({"hip hop": 88, "electronic": 72, "experimental": 66, "pop": 44}),
        themes=theme_profile({"rage": 92, "party": 89, "euphoria": 86, "existential": 45}),
        skills=skill_profile({"lyrics": 58, "vocals": 78, "production": 90, "mix/master": 75}),
        popularity=93.0,
        quality_consistency=70,
        release_tendency=45,
        friendliness=39,
        controversy=81,
        aggression=77,
        feature_cost=260000,
    ),
    EcosystemArtistSeed(
        name="A$AP Rocky",
        role="rapper",
        genres=genre_profile({"hip hop": 87, "experimental": 71, "electronic": 52, "rock": 34}),
        themes=theme_profile({"street life": 73, "party": 71, "fashion": 18, "euphoria": 61, "love": 44}),
        skills=skill_profile({"lyrics": 77, "vocals": 72, "production": 68, "mix/master": 56}),
        popularity=82.0,
        quality_consistency=71,
        release_tendency=10,
        friendliness=52,
        controversy=62,
        aggression=65,
        feature_cost=130000,
    ),
    EcosystemArtistSeed(
        name="Freddie Gibbs",
        role="rapper",
        genres=genre_profile({"hip hop": 95, "jazz": 38, "soul": 40}),
        themes=theme_profile({"street life": 96, "rage": 78, "nostalgia": 58}),
        skills=skill_profile({"lyrics": 94, "vocals": 79, "production": 52, "mix/master": 44}),
        popularity=69.0,
        quality_consistency=88,
        release_tendency=25,
        friendliness=34,
        controversy=70,
        aggression=88,
        feature_cost=65000,
    ),
    EcosystemArtistSeed(
        name="Pusha T",
        role="rapper",
        genres=genre_profile({"hip hop": 94, "soul": 42}),
        themes=theme_profile({"street life": 95, "rage": 74, "nostalgia": 64}),
        skills=skill_profile({"lyrics": 92, "vocals": 76, "production": 46, "mix/master": 44}),
        popularity=73.0,
        quality_consistency=85,
        release_tendency=42,
        friendliness=31,
        controversy=66,
        aggression=84,
        feature_cost=90000,
    ),
    EcosystemArtistSeed(
        name="The Weeknd",
        role="singer",
        genres=genre_profile({"r&b": 94, "pop": 91, "electronic": 74, "soul": 67}),
        themes=theme_profile({"heartbreak": 97, "love": 90, "party": 81, "existential": 65}),
        skills=skill_profile({"lyrics": 74, "vocals": 97, "production": 69, "mix/master": 63}),
        popularity=97.0,
        quality_consistency=90,
        release_tendency=34,
        friendliness=49,
        controversy=58,
        aggression=41,
        feature_cost=340000,
    ),
    EcosystemArtistSeed(
        name="Frank Ocean",
        role="singer-writer",
        genres=genre_profile({"r&b": 93, "soul": 87, "pop": 64, "experimental": 71, "folk": 44}),
        themes=theme_profile({"heartbreak": 91, "nostalgia": 96, "love": 84, "existential": 89}),
        skills=skill_profile({"lyrics": 91, "vocals": 92, "production": 72, "mix/master": 60}),
        popularity=89.0,
        quality_consistency=95,
        release_tendency=0.000000000000000001,
        friendliness=44,
        controversy=30,
        aggression=18,
        feature_cost=500000,
    ),
    EcosystemArtistSeed(
        name="Billie Eilish",
        role="singer-writer",
        genres=genre_profile({"pop": 90, "electronic": 74, "experimental": 70, "r&b": 41}),
        themes=theme_profile({"heartbreak": 76, "existential": 90, "rage": 55, "nostalgia": 64}),
        skills=skill_profile({"lyrics": 84, "vocals": 91, "production": 66, "mix/master": 60}),
        popularity=95.0,
        quality_consistency=87,
        release_tendency=40,
        friendliness=62,
        controversy=47,
        aggression=36,
        feature_cost=280000,
    ),
    EcosystemArtistSeed(
        name="Dijon",
        role="singer-writer",
        genres=genre_profile({"r&b": 82, "folk": 58, "soul": 72, "experimental": 51}),
        themes=theme_profile({"love": 77, "heartbreak": 82, "nostalgia": 74, "existential": 68}),
        skills=skill_profile({"lyrics": 80, "vocals": 88, "production": 63, "mix/master": 53}),
        popularity=52.0,
        quality_consistency=81,
        release_tendency=30,
        friendliness=71,
        controversy=18,
        aggression=20,
        feature_cost=25000,
    ),
    EcosystemArtistSeed(
        name="SZA",
        role="singer-writer",
        genres=genre_profile({"r&b": 94, "pop": 76, "soul": 78}),
        themes=theme_profile({"love": 90, "heartbreak": 93, "existential": 76, "nostalgia": 64}),
        skills=skill_profile({"lyrics": 86, "vocals": 92, "production": 58, "mix/master": 52}),
        popularity=91.0,
        quality_consistency=86,
        release_tendency=44,
        friendliness=68,
        controversy=37,
        aggression=28,
        feature_cost=200000,
    ),
    EcosystemArtistSeed(
        name="Lorde",
        role="singer-writer",
        genres=genre_profile({"pop": 88, "folk": 49, "electronic": 57, "experimental": 44}),
        themes=theme_profile({"nostalgia": 83, "existential": 87, "love": 62, "euphoria": 54}),
        skills=skill_profile({"lyrics": 87, "vocals": 84, "production": 60, "mix/master": 51}),
        popularity=79.0,
        quality_consistency=88,
        release_tendency=26,
        friendliness=55,
        controversy=24,
        aggression=22,
        feature_cost=110000,
    ),
    EcosystemArtistSeed(
        name="Olivia Rodrigo",
        role="singer-writer",
        genres=genre_profile({"pop": 90, "rock": 72, "punk": 60, "folk": 36}),
        themes=theme_profile({"heartbreak": 94, "rage": 77, "love": 82, "nostalgia": 58}),
        skills=skill_profile({"lyrics": 83, "vocals": 88, "production": 51, "mix/master": 48}),
        popularity=90.0,
        quality_consistency=80,
        release_tendency=43,
        friendliness=73,
        controversy=32,
        aggression=44,
        feature_cost=150000,
    ),
    EcosystemArtistSeed(
        name="Harry Styles",
        role="singer",
        genres=genre_profile({"pop": 91, "rock": 61, "folk": 42, "soul": 40}),
        themes=theme_profile({"love": 84, "heartbreak": 72, "nostalgia": 66, "euphoria": 74}),
        skills=skill_profile({"lyrics": 68, "vocals": 89, "production": 46, "mix/master": 45}),
        popularity=93.0,
        quality_consistency=76,
        release_tendency=55,
        friendliness=82,
        controversy=29,
        aggression=16,
        feature_cost=220000,
    ),
    EcosystemArtistSeed(
        name="Halsey",
        role="singer-writer",
        genres=genre_profile({"pop": 84, "rock": 58, "electronic": 52, "punk": 41}),
        themes=theme_profile({"heartbreak": 84, "existential": 79, "rage": 63, "love": 66}),
        skills=skill_profile({"lyrics": 76, "vocals": 80, "production": 47, "mix/master": 45}),
        popularity=74.0,
        quality_consistency=70,
        release_tendency=59,
        friendliness=57,
        controversy=44,
        aggression=48,
        feature_cost=70000,
    ),
    EcosystemArtistSeed(
        name="Troye Sivan",
        role="singer",
        genres=genre_profile({"pop": 85, "electronic": 58, "r&b": 46}),
        themes=theme_profile({"love": 88, "heartbreak": 71, "euphoria": 66, "nostalgia": 51}),
        skills=skill_profile({"lyrics": 69, "vocals": 82, "production": 43, "mix/master": 42}),
        popularity=68.0,
        quality_consistency=73,
        release_tendency=56,
        friendliness=78,
        controversy=16,
        aggression=14,
        feature_cost=50000,
    ),
    EcosystemArtistSeed(
        name="Bon Iver",
        role="singer-writer",
        genres=genre_profile({"folk": 96, "experimental": 73, "pop": 41, "soul": 46}),
        themes=theme_profile({"heartbreak": 74, "nostalgia": 92, "spirituality": 77, "existential": 82}),
        skills=skill_profile({"lyrics": 85, "vocals": 88, "production": 71, "mix/master": 58}),
        popularity=67.0,
        quality_consistency=89,
        release_tendency=12,
        friendliness=69,
        controversy=17,
        aggression=12,
        feature_cost=85000,
    ),
    EcosystemArtistSeed(
        name="Phoebe Bridgers",
        role="singer-writer",
        genres=genre_profile({"folk": 92, "rock": 53, "pop": 34}),
        themes=theme_profile({"heartbreak": 89, "existential": 86, "nostalgia": 84, "love": 51}),
        skills=skill_profile({"lyrics": 89, "vocals": 81, "production": 49, "mix/master": 44}),
        popularity=71.0,
        quality_consistency=85,
        release_tendency=39,
        friendliness=63,
        controversy=27,
        aggression=24,
        feature_cost=65000,
    ),
    EcosystemArtistSeed(
        name="Clairo",
        role="singer-writer",
        genres=genre_profile({"pop": 74, "folk": 63, "r&b": 48, "electronic": 39}),
        themes=theme_profile({"love": 77, "nostalgia": 73, "heartbreak": 68, "existential": 55}),
        skills=skill_profile({"lyrics": 72, "vocals": 76, "production": 53, "mix/master": 45}),
        popularity=66.0,
        quality_consistency=74,
        release_tendency=48,
        friendliness=80,
        controversy=14,
        aggression=11,
        feature_cost=45000,
    ),
    EcosystemArtistSeed(
        name="Tame Impala",
        role="artist-producer",
        genres=genre_profile({"rock": 92, "electronic": 78, "pop": 59, "experimental": 69}),
        themes=theme_profile({"nostalgia": 88, "euphoria": 84, "existential": 79, "love": 50}),
        skills=skill_profile({"lyrics": 64, "vocals": 80, "production": 96, "mix/master": 86}),
        popularity=83.0,
        quality_consistency=89,
        release_tendency=13,
        friendliness=66,
        controversy=18,
        aggression=17,
        feature_cost=180000,
    ),
    EcosystemArtistSeed(
        name="Mac DeMarco",
        role="singer-writer",
        genres=genre_profile({"rock": 79, "folk": 74, "pop": 35, "jazz": 34}),
        themes=theme_profile({"nostalgia": 79, "love": 62, "euphoria": 54, "existential": 48}),
        skills=skill_profile({"lyrics": 68, "vocals": 73, "production": 69, "mix/master": 56}),
        popularity=61.0,
        quality_consistency=73,
        release_tendency=52,
        friendliness=81,
        controversy=22,
        aggression=15,
        feature_cost=35000,
    ),
    EcosystemArtistSeed(
        name="Rex Orange County",
        role="singer-writer",
        genres=genre_profile({"pop": 76, "folk": 61, "soul": 48, "rock": 36}),
        themes=theme_profile({"love": 79, "nostalgia": 71, "heartbreak": 69, "euphoria": 52}),
        skills=skill_profile({"lyrics": 70, "vocals": 77, "production": 51, "mix/master": 43}),
        popularity=63.0,
        quality_consistency=69,
        release_tendency=50,
        friendliness=72,
        controversy=21,
        aggression=18,
        feature_cost=40000,
    ),
    EcosystemArtistSeed(
        name="Arctic Monkeys",
        role="band",
        genres=genre_profile({"rock": 95, "punk": 57, "blues": 51}),
        themes=theme_profile({"love": 73, "nostalgia": 70, "rage": 49, "existential": 59}),
        skills=skill_profile({"lyrics": 86, "vocals": 83, "production": 62, "mix/master": 54}),
        popularity=82.0,
        quality_consistency=84,
        release_tendency=34,
        friendliness=47,
        controversy=31,
        aggression=27,
        feature_cost=130000,
    ),
    EcosystemArtistSeed(
        name="The 1975",
        role="band",
        genres=genre_profile({"pop": 82, "rock": 76, "electronic": 68, "experimental": 49}),
        themes=theme_profile({"love": 76, "nostalgia": 80, "existential": 73, "party": 51}),
        skills=skill_profile({"lyrics": 79, "vocals": 78, "production": 70, "mix/master": 60}),
        popularity=76.0,
        quality_consistency=74,
        release_tendency=58,
        friendliness=43,
        controversy=52,
        aggression=39,
        feature_cost=95000,
    ),
    EcosystemArtistSeed(
        name="Glass Animals",
        role="band",
        genres=genre_profile({"pop": 71, "electronic": 78, "rock": 52, "experimental": 47}),
        themes=theme_profile({"love": 63, "euphoria": 75, "nostalgia": 56, "party": 52}),
        skills=skill_profile({"lyrics": 64, "vocals": 74, "production": 79, "mix/master": 63}),
        popularity=69.0,
        quality_consistency=71,
        release_tendency=46,
        friendliness=66,
        controversy=20,
        aggression=16,
        feature_cost=60000,
    ),
    EcosystemArtistSeed(
        name="Cigarettes After Sex",
        role="band",
        genres=genre_profile({"pop": 62, "folk": 58, "rock": 48, "soul": 34}),
        themes=theme_profile({"love": 91, "heartbreak": 88, "nostalgia": 66}),
        skills=skill_profile({"lyrics": 71, "vocals": 79, "production": 57, "mix/master": 52}),
        popularity=64.0,
        quality_consistency=83,
        release_tendency=29,
        friendliness=58,
        controversy=8,
        aggression=6,
        feature_cost=45000,
    ),
    EcosystemArtistSeed(
        name="Kanye West",
        role="artist-producer",
        genres=genre_profile({"hip hop": 94, "soul": 69, "electronic": 72, "pop": 61, "experimental": 79}),
        themes=theme_profile({"protest": 74, "spirituality": 89, "street life": 61, "rage": 82, "existential": 67}),
        skills=skill_profile({"lyrics": 74, "vocals": 66, "production": 99, "mix/master": 74}),
        popularity=95.0,
        quality_consistency=78,
        release_tendency=72,
        friendliness=19,
        controversy=99,
        aggression=96,
        feature_cost=420000,
    ),
    EcosystemArtistSeed(
        name="Metro Boomin",
        role="producer",
        genres=genre_profile({"hip hop": 95, "electronic": 63, "r&b": 42}),
        themes=theme_profile({"street life": 72, "party": 74, "rage": 84, "euphoria": 61}),
        skills=skill_profile({"lyrics": 20, "vocals": 18, "production": 98, "mix/master": 79}),
        popularity=88.0,
        quality_consistency=82,
        release_tendency=79,
        friendliness=46,
        controversy=29,
        aggression=41,
        feature_cost=175000,
    ),
    EcosystemArtistSeed(
        name="Rick Rubin",
        role="producer",
        genres=genre_profile({"hip hop": 81, "rock": 87, "metal": 74, "country": 48}),
        themes=theme_profile({"rage": 62, "protest": 56, "spirituality": 51, "street life": 44}),
        skills=skill_profile({"lyrics": 18, "vocals": 18, "production": 97, "mix/master": 84}),
        popularity=79.0,
        quality_consistency=88,
        release_tendency=41,
        friendliness=61,
        controversy=14,
        aggression=12,
        feature_cost=230000,
    ),
    EcosystemArtistSeed(
        name="Pharrell Williams",
        role="producer",
        genres=genre_profile({"pop": 87, "hip hop": 83, "r&b": 81, "soul": 62, "electronic": 54}),
        themes=theme_profile({"party": 82, "love": 75, "euphoria": 78, "nostalgia": 52}),
        skills=skill_profile({"lyrics": 50, "vocals": 64, "production": 96, "mix/master": 80}),
        popularity=85.0,
        quality_consistency=86,
        release_tendency=63,
        friendliness=78,
        controversy=17,
        aggression=15,
        feature_cost=210000,
    ),
    EcosystemArtistSeed(
        name="Jack Antonoff",
        role="producer",
        genres=genre_profile({"pop": 92, "rock": 58, "folk": 63, "electronic": 44}),
        themes=theme_profile({"love": 78, "heartbreak": 73, "nostalgia": 85, "existential": 54}),
        skills=skill_profile({"lyrics": 42, "vocals": 36, "production": 94, "mix/master": 78}),
        popularity=82.0,
        quality_consistency=85,
        release_tendency=76,
        friendliness=71,
        controversy=18,
        aggression=12,
        feature_cost=185000,
    ),
    EcosystemArtistSeed(
        name="Finneas",
        role="producer",
        genres=genre_profile({"pop": 88, "electronic": 58, "rock": 47, "experimental": 41}),
        themes=theme_profile({"heartbreak": 62, "existential": 67, "nostalgia": 58, "love": 55}),
        skills=skill_profile({"lyrics": 54, "vocals": 48, "production": 92, "mix/master": 79}),
        popularity=73.0,
        quality_consistency=87,
        release_tendency=68,
        friendliness=74,
        controversy=14,
        aggression=10,
        feature_cost=120000,
    ),
    EcosystemArtistSeed(
        name="Mike Dean",
        role="producer",
        genres=genre_profile({"hip hop": 78, "electronic": 76, "pop": 51, "rock": 44, "experimental": 57}),
        themes=theme_profile({"rage": 68, "euphoria": 71, "street life": 46, "existential": 40}),
        skills=skill_profile({"lyrics": 16, "vocals": 14, "production": 95, "mix/master": 97}),
        popularity=74.0,
        quality_consistency=91,
        release_tendency=71,
        friendliness=47,
        controversy=19,
        aggression=18,
        feature_cost=140000,
    ),
    EcosystemArtistSeed(
        name="Hit-Boy",
        role="producer",
        genres=genre_profile({"hip hop": 91, "pop": 51, "r&b": 49}),
        themes=theme_profile({"street life": 69, "party": 58, "protest": 44, "rage": 57}),
        skills=skill_profile({"lyrics": 20, "vocals": 18, "production": 94, "mix/master": 77}),
        popularity=72.0,
        quality_consistency=84,
        release_tendency=74,
        friendliness=59,
        controversy=17,
        aggression=19,
        feature_cost=90000,
    ),
    EcosystemArtistSeed(
        name="Madlib",
        role="producer",
        genres=genre_profile({"hip hop": 86, "jazz": 79, "soul": 74, "experimental": 88}),
        themes=theme_profile({"street life": 54, "nostalgia": 75, "existential": 42, "rage": 47}),
        skills=skill_profile({"lyrics": 10, "vocals": 10, "production": 98, "mix/master": 72}),
        popularity=67.0,
        quality_consistency=93,
        release_tendency=57,
        friendliness=36,
        controversy=13,
        aggression=14,
        feature_cost=100000,
    ),
    EcosystemArtistSeed(
        name="Kaytranada",
        role="producer",
        genres=genre_profile({"electronic": 93, "r&b": 72, "hip hop": 66, "pop": 58, "soul": 54}),
        themes=theme_profile({"party": 82, "love": 56, "euphoria": 87, "nostalgia": 48}),
        skills=skill_profile({"lyrics": 14, "vocals": 18, "production": 96, "mix/master": 83}),
        popularity=76.0,
        quality_consistency=87,
        release_tendency=66,
        friendliness=75,
        controversy=15,
        aggression=12,
        feature_cost=95000,
    ),
    EcosystemArtistSeed(
        name="Serban Ghenea",
        role="mix-engineer",
        genres=genre_profile({"pop": 88, "r&b": 72, "hip hop": 65, "rock": 52}),
        themes=theme_profile({"love": 40, "party": 39, "heartbreak": 41, "euphoria": 37}),
        skills=skill_profile({"lyrics": 5, "vocals": 8, "production": 86, "mix/master": 99}),
        popularity=71.0,
        quality_consistency=98,
        release_tendency=82,
        friendliness=63,
        controversy=7,
        aggression=4,
        feature_cost=110000,
    ),
    EcosystemArtistSeed(
        name="Manny Marroquin",
        role="mix-engineer",
        genres=genre_profile({"pop": 86, "r&b": 81, "hip hop": 74, "rock": 58}),
        themes=theme_profile({"love": 37, "heartbreak": 36, "party": 39, "euphoria": 34}),
        skills=skill_profile({"lyrics": 5, "vocals": 8, "production": 84, "mix/master": 98}),
        popularity=69.0,
        quality_consistency=97,
        release_tendency=79,
        friendliness=58,
        controversy=8,
        aggression=4,
        feature_cost=100000,
    ),
    EcosystemArtistSeed(
        name="Chris Lord-Alge",
        role="mix-engineer",
        genres=genre_profile({"rock": 92, "pop": 71, "punk": 63, "metal": 69}),
        themes=theme_profile({"rage": 42, "party": 34, "nostalgia": 32, "love": 28}),
        skills=skill_profile({"lyrics": 4, "vocals": 7, "production": 82, "mix/master": 98}),
        popularity=67.0,
        quality_consistency=96,
        release_tendency=74,
        friendliness=39,
        controversy=9,
        aggression=8,
        feature_cost=95000,
    ),
    EcosystemArtistSeed(
        name="Jaycen Joshua",
        role="mix-engineer",
        genres=genre_profile({"hip hop": 84, "pop": 76, "r&b": 79, "electronic": 54}),
        themes=theme_profile({"party": 38, "love": 34, "heartbreak": 33, "euphoria": 35}),
        skills=skill_profile({"lyrics": 4, "vocals": 8, "production": 83, "mix/master": 97}),
        popularity=68.0,
        quality_consistency=97,
        release_tendency=76,
        friendliness=56,
        controversy=8,
        aggression=4,
        feature_cost=100000,
    ),
    EcosystemArtistSeed(
        name="Tony Maserati",
        role="mix-engineer",
        genres=genre_profile({"r&b": 84, "pop": 76, "hip hop": 63, "soul": 58}),
        themes=theme_profile({"love": 37, "heartbreak": 39, "party": 31, "nostalgia": 29}),
        skills=skill_profile({"lyrics": 4, "vocals": 7, "production": 80, "mix/master": 96}),
        popularity=60.0,
        quality_consistency=94,
        release_tendency=69,
        friendliness=52,
        controversy=6,
        aggression=4,
        feature_cost=80000,
    ),
    EcosystemArtistSeed(
        name="Dave Pensado",
        role="mix-engineer",
        genres=genre_profile({"pop": 79, "r&b": 73, "hip hop": 61, "rock": 49}),
        themes=theme_profile({"love": 29, "party": 31, "heartbreak": 28, "euphoria": 26}),
        skills=skill_profile({"lyrics": 4, "vocals": 7, "production": 81, "mix/master": 95}),
        popularity=58.0,
        quality_consistency=95,
        release_tendency=66,
        friendliness=65,
        controversy=5,
        aggression=3,
        feature_cost=78000,
    ),
    EcosystemArtistSeed(
        name="Bob Ludwig",
        role="mastering-engineer",
        genres=genre_profile({"pop": 82, "rock": 78, "classical": 66, "jazz": 58}),
        themes=theme_profile({"nostalgia": 26, "love": 22, "heartbreak": 22, "spirituality": 24}),
        skills=skill_profile({"lyrics": 3, "vocals": 6, "production": 78, "mix/master": 99}),
        popularity=64.0,
        quality_consistency=99,
        release_tendency=59,
        friendliness=71,
        controversy=3,
        aggression=2,
        feature_cost=90000,
    ),
    EcosystemArtistSeed(
        name="Emily Lazar",
        role="mastering-engineer",
        genres=genre_profile({"pop": 84, "rock": 66, "electronic": 62, "r&b": 58}),
        themes=theme_profile({"love": 24, "heartbreak": 23, "euphoria": 25, "nostalgia": 24}),
        skills=skill_profile({"lyrics": 3, "vocals": 6, "production": 79, "mix/master": 98}),
        popularity=57.0,
        quality_consistency=98,
        release_tendency=64,
        friendliness=74,
        controversy=4,
        aggression=2,
        feature_cost=72000,
    ),
    EcosystemArtistSeed(
        name="Randy Merrill",
        role="mastering-engineer",
        genres=genre_profile({"pop": 82, "hip hop": 69, "r&b": 63, "electronic": 57}),
        themes=theme_profile({"party": 23, "love": 22, "heartbreak": 21, "euphoria": 24}),
        skills=skill_profile({"lyrics": 3, "vocals": 6, "production": 80, "mix/master": 98}),
        popularity=56.0,
        quality_consistency=98,
        release_tendency=68,
        friendliness=61,
        controversy=4,
        aggression=2,
        feature_cost=70000,
    ),
    EcosystemArtistSeed(
        name="Mike Bozzi",
        role="mastering-engineer",
        genres=genre_profile({"hip hop": 77, "pop": 72, "r&b": 61, "electronic": 49}),
        themes=theme_profile({"street life": 23, "party": 22, "love": 21, "rage": 24}),
        skills=skill_profile({"lyrics": 3, "vocals": 6, "production": 79, "mix/master": 97}),
        popularity=51.0,
        quality_consistency=96,
        release_tendency=61,
        friendliness=54,
        controversy=5,
        aggression=3,
        feature_cost=62000,
    ),
]

# Load extra seed specs in a separate module to keep this file readable.
from rapsim_reviews.artist_ecosystem_seed_extra import (  # noqa: E402
    EXTRA_SEED_SPECS,
    FAMOUS_SEED_SPECS,
    GROWING_SEED_SPECS,
)


def _seed_from_spec(spec: tuple) -> EcosystemArtistSeed:
    # Specs can optionally include base overrides for genre/theme/skill profile construction.
    # Base layout (12 fields):
    # (name, role, genres, themes, skills, popularity, qc, tendency, friendliness, controversy, aggression, cost)
    # Optional tail (3 fields): (base_genre, base_theme, base_skill)
    if len(spec) not in (12, 15):
        raise ValueError(f"Bad seed spec length: {len(spec)} for {spec[0]}")
    (
        name,
        role,
        genre_overrides,
        theme_overrides,
        skill_overrides,
        popularity,
        qc,
        tendency,
        friendliness,
        controversy,
        aggression,
        cost,
        *tail,
    ) = spec
    base_genre = 18
    base_theme = 18
    base_skill = 20
    if tail:
        base_genre, base_theme, base_skill = tail
    return EcosystemArtistSeed(
        name=str(name),
        role=str(role),
        genres=genre_profile(dict(genre_overrides), base=int(base_genre)),
        themes=theme_profile(dict(theme_overrides), base=int(base_theme)),
        skills=skill_profile(dict(skill_overrides), base=int(base_skill)),
        popularity=float(popularity),
        quality_consistency=int(qc),
        release_tendency=int(tendency),
        friendliness=int(friendliness),
        controversy=int(controversy),
        aggression=int(aggression),
        feature_cost=int(cost),
    )


_existing_names = {s.name for s in ARTIST_ECOSYSTEM_SEEDS}
for _spec in list(EXTRA_SEED_SPECS) + list(FAMOUS_SEED_SPECS) + list(GROWING_SEED_SPECS):
    if _spec[0] in _existing_names:
        continue
    ARTIST_ECOSYSTEM_SEEDS.append(_seed_from_spec(_spec))
    _existing_names.add(_spec[0])


BATTLE_SKILLS_BY_NAME: dict[str, int] = {
    "Kendrick Lamar": 97,
    "Eminem": 99,
    "Drake": 72,
    "Kanye West": 65,
    "J. Cole": 88,
    "Lil Wayne": 91,
    "Nicki Minaj": 85,
    "Jay-Z": 94,
    "Pusha T": 96,
    "Tyler, The Creator": 78,
    "A$AP Rocky": 68,
    "Future": 45,
    "Travis Scott": 40,
    "21 Savage": 71,
    "Playboi Carti": 30,
    "Frank Ocean": 25,
    "SZA": 30,
    "Doja Cat": 55,
}
ARTIST_ECOSYSTEM_SEEDS = [
    replace(seed, battle_skills=int(BATTLE_SKILLS_BY_NAME.get(seed.name, seed.battle_skills)))
    for seed in ARTIST_ECOSYSTEM_SEEDS
]


ARTIST_GENDER_BY_NAME: dict[str, str] = {
    "Billie Eilish": "female",
    "SZA": "female",
    "Lorde": "female",
    "Olivia Rodrigo": "female",
    "Halsey": "female",
    "Phoebe Bridgers": "female",
    "Clairo": "female",
    "Emily Lazar": "female",
    "Taylor Swift": "female",
    "Beyonce": "female",
    "Rihanna": "female",
    "Ariana Grande": "female",
    "Adele": "female",
    "Dua Lipa": "female",
    "Doja Cat": "female",
    "Kali Uchis": "female",
    "Lana Del Rey": "female",
    "Rosalia": "female",
    "Nicki Minaj": "female",
    "Megan Thee Stallion": "female",
    "Cardi B": "female",
    "Charli XCX": "female",
    "FKA twigs": "female",
    "Sabrina Carpenter": "female",
    "Kacey Musgraves": "female",
    "Mitski": "female",
    "Neon Kairo": "female",
    "Saffron Skye": "female",
    "Velvet Dime": "female",
    "Cobalt Garden": "female",
    "Raven County": "female",
    "Chrome Lullaby": "female",
    "Midnight Pollen": "female",
    "Sunny Switch": "female",
    "Soda Eclipse": "female",
    "Paramore": "female",
}

for _seed in ARTIST_ECOSYSTEM_SEEDS:
    object.__setattr__(_seed, "gender", ARTIST_GENDER_BY_NAME.get(_seed.name, "male"))
    object.__setattr__(_seed, "sexuality", None)
    object.__setattr__(_seed, "romance_preference", _hidden_romance_preference_for_name(_seed.name))


ARTIST_RELEASE_COOLOFFS: dict[str, dict[str, int]] = {
    "Eminem": {"single": 16, "ep": 36, "mixtape": 44, "album": 130},
    "Kendrick Lamar": {"single": 18, "ep": 40, "mixtape": 52, "album": 120},
    "J. Cole": {"single": 14, "ep": 30, "mixtape": 42, "album": 95},
    "Drake": {"single": 6, "ep": 20, "mixtape": 28, "album": 60},
    "Tyler, The Creator": {"single": 12, "ep": 28, "mixtape": 38, "album": 90},
    "Baby Keem": {"single": 10, "ep": 22, "mixtape": 26, "album": 72},
    "Travis Scott": {"single": 10, "ep": 28, "mixtape": 34, "album": 95},
    "A$AP Rocky": {"single": 14, "ep": 34, "mixtape": 42, "album": 110},
    "Freddie Gibbs": {"single": 10, "ep": 20, "mixtape": 24, "album": 55},
    "Pusha T": {"single": 16, "ep": 34, "mixtape": 46, "album": 105},
    "The Weeknd": {"single": 8, "ep": 20, "mixtape": 34, "album": 75},
    "Frank Ocean": {"single": 26, "ep": 80, "mixtape": 120, "album": 200},
    "Billie Eilish": {"single": 8, "ep": 22, "mixtape": 40, "album": 70},
    "Dijon": {"single": 14, "ep": 30, "mixtape": 42, "album": 88},
    "SZA": {"single": 10, "ep": 24, "mixtape": 34, "album": 78},
    "Lorde": {"single": 18, "ep": 42, "mixtape": 60, "album": 125},
    "Olivia Rodrigo": {"single": 8, "ep": 20, "mixtape": 34, "album": 68},
    "Harry Styles": {"single": 10, "ep": 24, "mixtape": 38, "album": 75},
    "Halsey": {"single": 8, "ep": 22, "mixtape": 34, "album": 70},
    "Troye Sivan": {"single": 10, "ep": 22, "mixtape": 32, "album": 68},
    "Bon Iver": {"single": 16, "ep": 34, "mixtape": 46, "album": 110},
    "Phoebe Bridgers": {"single": 12, "ep": 28, "mixtape": 40, "album": 96},
    "Clairo": {"single": 10, "ep": 24, "mixtape": 36, "album": 80},
    "Tame Impala": {"single": 14, "ep": 30, "mixtape": 44, "album": 118},
    "Mac DeMarco": {"single": 10, "ep": 20, "mixtape": 30, "album": 62},
    "Rex Orange County": {"single": 10, "ep": 24, "mixtape": 34, "album": 72},
    "Arctic Monkeys": {"single": 14, "ep": 30, "mixtape": 999, "album": 95},
    "The 1975": {"single": 10, "ep": 24, "mixtape": 999, "album": 78},
    "Glass Animals": {"single": 10, "ep": 24, "mixtape": 999, "album": 88},
    "Cigarettes After Sex": {"single": 14, "ep": 26, "mixtape": 999, "album": 105},
    "Kanye West": {"single": 8, "ep": 20, "mixtape": 26, "album": 78},
    "Metro Boomin": {"single": 8, "ep": 18, "mixtape": 22, "album": 52},
    "Rick Rubin": {"single": 16, "ep": 26, "mixtape": 999, "album": 70},
    "Pharrell Williams": {"single": 10, "ep": 22, "mixtape": 28, "album": 68},
    "Jack Antonoff": {"single": 8, "ep": 18, "mixtape": 999, "album": 56},
    "Finneas": {"single": 8, "ep": 20, "mixtape": 999, "album": 64},
    "Mike Dean": {"single": 8, "ep": 18, "mixtape": 999, "album": 70},
    "Hit-Boy": {"single": 8, "ep": 18, "mixtape": 24, "album": 58},
    "Madlib": {"single": 12, "ep": 22, "mixtape": 26, "album": 74},
    "Kaytranada": {"single": 10, "ep": 22, "mixtape": 28, "album": 66},
    "Serban Ghenea": {"single": 6, "ep": 14, "mixtape": 999, "album": 34},
    "Manny Marroquin": {"single": 6, "ep": 14, "mixtape": 999, "album": 34},
    "Chris Lord-Alge": {"single": 6, "ep": 16, "mixtape": 999, "album": 38},
    "Jaycen Joshua": {"single": 6, "ep": 14, "mixtape": 999, "album": 34},
    "Tony Maserati": {"single": 6, "ep": 14, "mixtape": 999, "album": 36},
    "Dave Pensado": {"single": 8, "ep": 16, "mixtape": 999, "album": 42},
    "Bob Ludwig": {"single": 8, "ep": 16, "mixtape": 999, "album": 48},
    "Emily Lazar": {"single": 8, "ep": 16, "mixtape": 999, "album": 44},
    "Randy Merrill": {"single": 8, "ep": 16, "mixtape": 999, "album": 42},
    "Mike Bozzi": {"single": 8, "ep": 16, "mixtape": 999, "album": 40},
}


ARTIST_BASE_REPUTATION: dict[str, int] = {
    "Eminem": 92,
    "Kendrick Lamar": 97,
    "J. Cole": 86,
    "Drake": 80,
    "Tyler, The Creator": 90,
    "Baby Keem": 72,
    "Travis Scott": 78,
    "A$AP Rocky": 82,
    "Freddie Gibbs": 89,
    "Pusha T": 88,
    "The Weeknd": 90,
    "Frank Ocean": 96,
    "Billie Eilish": 88,
    "Dijon": 79,
    "SZA": 87,
    "Lorde": 90,
    "Olivia Rodrigo": 84,
    "Harry Styles": 83,
    "Halsey": 74,
    "Troye Sivan": 76,
    "Bon Iver": 90,
    "Phoebe Bridgers": 88,
    "Clairo": 78,
    "Tame Impala": 92,
    "Mac DeMarco": 80,
    "Rex Orange County": 73,
    "Arctic Monkeys": 91,
    "The 1975": 79,
    "Glass Animals": 76,
    "Cigarettes After Sex": 77,
    "Kanye West": 86,
    "Metro Boomin": 85,
    "Rick Rubin": 95,
    "Pharrell Williams": 92,
    "Jack Antonoff": 86,
    "Finneas": 81,
    "Mike Dean": 88,
    "Hit-Boy": 83,
    "Madlib": 94,
    "Kaytranada": 86,
    "Serban Ghenea": 96,
    "Manny Marroquin": 94,
    "Chris Lord-Alge": 93,
    "Jaycen Joshua": 90,
    "Tony Maserati": 88,
    "Dave Pensado": 92,
    "Bob Ludwig": 97,
    "Emily Lazar": 92,
    "Randy Merrill": 91,
    "Mike Bozzi": 86,
}


ARTIST_LOVINGNESS: dict[str, int] = {
    "Eminem": 18,
    "Kendrick Lamar": 28,
    "J. Cole": 42,
    "Drake": 65,
    "Tyler, The Creator": 34,
    "Baby Keem": 48,
    "Travis Scott": 40,
    "A$AP Rocky": 58,
    "Freddie Gibbs": 22,
    "Pusha T": 20,
    "The Weeknd": 55,
    "Frank Ocean": 46,
    "Billie Eilish": 62,
    "Dijon": 66,
    "SZA": 71,
    "Lorde": 44,
    "Olivia Rodrigo": 72,
    "Harry Styles": 78,
    "Halsey": 56,
    "Troye Sivan": 74,
    "Bon Iver": 38,
    "Phoebe Bridgers": 51,
    "Clairo": 64,
    "Tame Impala": 33,
    "Mac DeMarco": 69,
    "Rex Orange County": 63,
    "Arctic Monkeys": 27,
    "The 1975": 36,
    "Glass Animals": 41,
    "Cigarettes After Sex": 52,
    "Kanye West": 14,
    "Metro Boomin": 24,
    "Rick Rubin": 20,
    "Pharrell Williams": 57,
    "Jack Antonoff": 45,
    "Finneas": 53,
    "Mike Dean": 19,
    "Hit-Boy": 31,
    "Madlib": 16,
    "Kaytranada": 54,
    "Serban Ghenea": 22,
    "Manny Marroquin": 24,
    "Chris Lord-Alge": 18,
    "Jaycen Joshua": 29,
    "Tony Maserati": 33,
    "Dave Pensado": 28,
    "Bob Ludwig": 25,
    "Emily Lazar": 31,
    "Randy Merrill": 27,
    "Mike Bozzi": 26,
}

ARTIST_ROMANCE_PREFERENCES: dict[str, str] = {
    seed.name: str(seed.romance_preference or "prefers_female")
    for seed in ARTIST_ECOSYSTEM_SEEDS
}


ARTIST_FEATURE_TURNAROUND: dict[str, int] = {
    "Eminem": 5,
    "Kendrick Lamar": 5,
    "J. Cole": 4,
    "Drake": 3,
    "Tyler, The Creator": 4,
    "Baby Keem": 3,
    "Travis Scott": 4,
    "A$AP Rocky": 5,
    "Freddie Gibbs": 3,
    "Pusha T": 4,
    "The Weeknd": 4,
    "Frank Ocean": 6,
    "Billie Eilish": 4,
    "Dijon": 4,
    "SZA": 5,
    "Lorde": 6,
    "Olivia Rodrigo": 4,
    "Harry Styles": 4,
    "Halsey": 3,
    "Troye Sivan": 3,
    "Bon Iver": 6,
    "Phoebe Bridgers": 5,
    "Clairo": 4,
    "Tame Impala": 6,
    "Mac DeMarco": 4,
    "Rex Orange County": 4,
    "Arctic Monkeys": 5,
    "The 1975": 4,
    "Glass Animals": 4,
    "Cigarettes After Sex": 5,
    "Kanye West": 6,
    "Metro Boomin": 3,
    "Rick Rubin": 5,
    "Pharrell Williams": 3,
    "Jack Antonoff": 3,
    "Finneas": 3,
    "Mike Dean": 4,
    "Hit-Boy": 3,
    "Madlib": 5,
    "Kaytranada": 4,
    "Serban Ghenea": 3,
    "Manny Marroquin": 3,
    "Chris Lord-Alge": 3,
    "Jaycen Joshua": 3,
    "Tony Maserati": 3,
    "Dave Pensado": 3,
    "Bob Ludwig": 4,
    "Emily Lazar": 4,
    "Randy Merrill": 3,
    "Mike Bozzi": 3,
}
